### ISSUE TITLE
Flag to allow ark commander to run on containers

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/ARKcommander#4]
Could we have a flag to overwrite Commander's default behavior and allow it to run on containers? I find containers more flexible for working in a high availability setup compared to qemu or xen. Travis has told me on Slack that this is intended as containers impose a security risk, but a well configured container should be isolated enough for running an application.

**Comment by faustbrian** [comment]
Commander will be integrated into Core v2 directly so closing this here.
